<?php
/**
 * v3 - Orden EXACTO de las 78 columnas de 'Template Empleados.xls'
 * (hoja 'Empleados'), con el origen del dato para cada una. Generado
 * automaticamente desde el Excel entregado por el usuario -- no
 * reordenar ni renombrar encabezados a mano, romperia la carga a Buk.
 *
 * Cada fila: [encabezado_excel, tabla|null, columna|null, tipo].
 * tabla=null significa columna gris o sin color: se exporta en blanco,
 * a peticion explicita del usuario (se completa directo en Buk).
 */

function columnasBuk(): array
{
    return [
        ["Tipo de Documento", "p", "tipo_documento", "texto"],
        ["Número de Documento*", "p", "rut", "texto"],
        ["Apellido*", "p", "apellido", "texto"],
        ["Segundo Apellido", "p", "segundo_apellido", "texto"],
        ["Nombre*", "p", "nombre", "texto"],
        ["Sexo*", "d", "sexo", "texto"],
        ["Nacionalidad*", "d", "nacionalidad", "texto"],
        ["Fecha de Nacimiento*", "d", "fecha_nacimiento", "fecha"],
        ["Estado Civil*", "d", "estado_civil", "texto"],
        ["Dirección*", "d", "direccion_exacta", "texto"],
        ["Región*", "d", "region", "texto"],
        ["Comuna*", "d", "comuna", "texto"],
        ["Ciudad", "d", "ciudad", "texto"],
        ["Teléfono Particular", "p", "telefono", "texto"],
        ["Teléfono Oficina", null, null, null],
        ["Email", null, null, null],
        ["Email Personal", "p", "correo", "texto"],
        ["País", "d", "pais", "texto"],
        ["Calle", null, null, null],
        ["Número de Calle", null, null, null],
        ["Depto / Oficina", null, null, null],
        ["Título", null, null, null],
        ["Institución", null, null, null],
        ["Código de Ficha*", "j", "codigo_ficha", "texto"],
        ["Ingreso Compañía*", "j", "ingreso_compania", "fecha"],
        ["Fecha de Inicio Cotización AFC", null, null, null],
        ["Fecha Inicio Vacaciones Progresivas", null, null, null],
        ["Forma de Pago*", "j", "forma_pago", "texto"],
        ["Banco", "d", "banco", "texto"],
        ["Tipo de Cuenta", "d", "tipo_cuenta", "texto"],
        ["Número de Cuenta", "d", "numero_cuenta", "texto"],
        ["Código de Sucursal", null, null, null],
        ["Tipo Vale Vista", null, null, null],
        ["Régimen Previsional*", "j", "regimen_previsional", "texto"],
        ["Fondo de Cotización", "d", "afp", "texto"],
        ["AFP Recaudadora", null, null, null],
        ["Aumentar la cotización en 1%*", null, null, null],
        ["Fonasa/Isapre*", "d", "isapre_fonasa", "texto"],
        ["Plan Isapre UF*", null, null, null],
        ["Plan Isapre Pesos*", null, null, null],
        ["Plan Isapre Porcentual*", null, null, null],
        ["AFC*", "j", "afc", "texto"],
        ["Jubilado", "j", "jubilado", "texto"],
        ["Régimen Jubilacion*", null, null, null],
        ["Cuenta 2", null, null, null],
        ["Plan Cuenta 2", null, null, null],
        ["Moneda", null, null, null],
        ["En Situación de Discapacidad", "j", "discapacidad", "texto"],
        ["Fecha de notificación de Discapacidad", null, null, null],
        ["En Situación de Invalidez", "j", "invalidez", "texto"],
        ["Fecha de notificación de Invalidez", null, null, null],
        ["Carga Simple", null, null, null],
        ["Carga Maternal", null, null, null],
        ["Carga Inválida", null, null, null],
        ["Tramo de Asignación", null, null, null],
        ["Escala Sueldo*", "j", "escala_sueldo", "texto"],
        ["Proceso*", "j", "proceso", "texto"],
        ["Tipo Transfer*", "j", "tipo_transfer", "texto"],
        ["Estudios*", "d", "estudios", "texto"],
        ["Contacto de Emergencia ", "d", "contacto_emergencia_telefono", "texto"],
        ["Fecha de Reconocimiento*", "j", "fecha_reconocimiento", "fecha"],
        ["Meses reconocidos", null, null, null],
        ["Nombre contacto Emergencia", "d", "contacto_emergencia_nombre", "texto"],
        ["Recomendado*", "j", "recomendado", "texto"],
        ["Fecha Indefinido", null, null, null],
        ["Bono de Obra", "j", "bono_obra", "texto"],
        ["Brecha_Pagada?", null, null, null],
        ["Registro Inicio Contrato", null, null, null],
        ["Registro Termino Contrato", null, null, null],
        ["Retención Judicial*", "j", "retencion_judicial", "texto"],
        ["Seguro Covid Fecha Inicio*", "j", "seguro_covid_fecha_inicio", "fecha"],
        ["Vale Vista Personalizado", null, null, null],
        ["OFICINA", null, null, null],
        ["TELE", null, null, null],
        ["Art 22?", null, null, null],
        ["Cambio de Jornada", null, null, null],
        ["Reajuste de Sueldo", null, null, null],
        ["Bono Target", null, null, null],
    ];
}