<?php
/**
 * v3 - Listas desplegables extraidas de la plantilla oficial 'Template
 * Empleados.xls' (hoja 'Listas') que se sube a Buk. Los valores son
 * EXACTOS a los que Buk espera -- no traducir, no reformatear.
 *
 * v3.3/v3.5 -- recortes pedidos por el usuario:
 *  - nacionalidad: solo Sudamerica + Mexico + Haiti (14 opciones).
 *  - fondo_cotizacion (AFP): las 7 vigentes + 4 regimenes antiguos
 *    (Servicios de Seguro Social, Empart) que aun pueden verse en
 *    trabajadores mayores. Se elimino todo desde 'Capremer' hacia abajo.
 *  - banco: bancos con banca retail en Chile + MACH, Tenpo Prepago SA
 *    y Mercadopago Emisora S.A. (billeteras que ICAFAL si acepta para pago).
 */

function listasBuk(): array
{
    return [
        'tipo_documento' => [
        "RUT",
        "Otro"
    ],
        'sexo' => [
        "M",
        "F"
    ],
        'nacionalidad' => [
        "Argentina",
        "Boliviana",
        "Brasileña",
        "Chilena",
        "Colombiana",
        "Ecuatoriana",
        "Guyanesa",
        "Haitiana",
        "Mexicana",
        "Paraguaya",
        "Peruana",
        "Surinamesa",
        "Uruguaya",
        "Venezolana"
    ],
        'estado_civil' => [
        "Soltero",
        "Casado",
        "Divorciado",
        "Viudo",
        "Acuerdo de Unión Civil"
    ],
        'region' => [
        "I: de Tarapacá",
        "II: de Antofagasta",
        "III: de Atacama",
        "IV: de Coquimbo",
        "V: de Valparaíso",
        "VI: del Libertador Gral. Bernardo O'Higgins",
        "VII: del Maule",
        "VIII: del Biobío",
        "IX: de la Araucanía",
        "X: de Los Lagos",
        "XI: de Aysén del Gral. Carlos Ibáñez del Campo",
        "XII: de Magallanes y de la Antártica Chilena",
        "RM: Metropolitana de Santiago",
        "XIV: de Los Ríos",
        "XV: de Arica y Parinacota",
        "XVI: de Ñuble"
    ],
        'forma_pago' => [
        "Cheque",
        "Servipag",
        "Vale Vista",
        "No Generar Pago",
        "Transferencia Bancaria"
    ],
        'banco' => [
        "Ripley",
        "Santander",
        "Scotiabank",
        "Security",
        "Tenpo Prepago SA",
        "Mercadopago Emisora S.A.",
        "MACH",
        "Itau",
        "BCI",
        "BICE",
        "Banco de Chile",
        "Consorcio",
        "COOPEUCH",
        "Corpbanca",
        "CrediChile",
        "Banco Estado",
        "Falabella",
        "Internacional"
    ],
        'tipo_cuenta' => [
        "Corriente",
        "Vista",
        "Ahorro"
    ],
        'regimen_previsional' => [
        "AFP",
        "No Cotiza",
        "IPS (Ex-INP)"
    ],
        'fondo_cotizacion' => [
        "Capital",
        "Cuprum",
        "Habitat",
        "Modelo",
        "PlanVital",
        "ProVida",
        "Uno",
        "Servicios de Seguro Social - Régimen 1",
        "Servicios de Seguro Social - Régimen 2",
        "Empart - Régimen 1",
        "Empart - Régimen 2"
    ],
        'fonasa_isapre' => [
        "Fonasa",
        "Banmedica",
        "Colmena",
        "Consalud",
        "Cruz Blanca",
        "Nueva Masvida",
        "Vida Tres",
        "Banco Estado",
        "ISALUD Isapre de Codelco",
        "Cruz del Norte",
        "Esencial",
        "Mutual",
        "No Cotiza Salud"
    ],
        'afc' => [
        "Menos de 11 Años",
        "Más de 11 Años",
        "No Cotiza"
    ],
        'jubilado' => [
        "Sí",
        "No"
    ],
        'estudios' => [
        "Primero Básico",
        "Segundo Básico",
        "Tercero Básico",
        "Cuarto Básico",
        "Quinto Básico",
        "Sexto Básico",
        "Séptimo Básico",
        "Octavo Básico",
        "Primero Medio",
        "Segundo Medio",
        "Tercero Medio",
        "Cuarto medio",
        "Quinto medio",
        "Militares",
        "Técnico Incompleto",
        "Técnico",
        "Técnico Universitario",
        "Técnico Universitario Incompleto",
        "Universitarios",
        "Universitarios Incompletos"
    ],
        'recomendado' => [
        "Si",
        "No"
    ],
        'retencion_judicial' => [
        "No está",
        "Está"
    ],
        'escala_sueldo' => [
        "Asig_Obra",
        "Asig_Sup_Tem",
        "Asig_Sup",
        "Asig_Ope",
        "Asig_Ger",
        "Asig_Pro",
        "Asig_Of_Tem",
        "Asig_Tec",
        "Asig_E1",
        "Asig_G1",
        "0_General",
        "1_Obra",
        "2_Obra",
        "3_Obra LyD",
        "Sup_01",
        "Sup_02",
        "Sup_03",
        "Sup_04",
        "Sup_05",
        "Sup_06",
        "Sup_07",
        "Sup_08",
        "Sup_09",
        "Sup_10",
        "Sup_11",
        "Sup_12",
        "Sup_13",
        "Sup_14",
        "Sup_15",
        "Sup_16",
        "Sup_17",
        "Sup_18",
        "Sup_19",
        "Sup_20",
        "Sup_21",
        "Sup_22",
        "Sup_23",
        "Sup_24",
        "Sup_25",
        "Sup_26",
        "Sup_27",
        "Sup_28",
        "Sup_29",
        "Sup_30",
        "Sup_31",
        "Sup_32",
        "Sup_33",
        "Sup_34",
        "Sup_35",
        "Sup_36",
        "Sup_37",
        "Sup_38",
        "Sup_39",
        "Sup_40",
        "Sup_41",
        "Sup_42",
        "Sup_43",
        "Sup_44",
        "Sup_45",
        "Sup_46",
        "Sup_47",
        "Sup_48",
        "Sup_49",
        "Sup_50",
        "Ope_01",
        "Ope_02",
        "Ope_03",
        "Ope_04",
        "Ope_05",
        "Ope_06",
        "Ope_07",
        "Ope_08",
        "Ope_09",
        "Ope_10",
        "Ope_11",
        "Ope_12",
        "Ope_13",
        "Ope_14",
        "Ope_15",
        "Ope_16",
        "Ope_17",
        "Ope_18",
        "Ope_19",
        "Ope_20",
        "Pro_01",
        "Pro_02",
        "Pro_03",
        "Pro_04",
        "Pro_05",
        "Pro_06",
        "Pro_07",
        "Pro_08",
        "Pro_09",
        "Pro_10",
        "Pro_11",
        "Pro_12",
        "Pro_13",
        "Pro_14",
        "Pro_15",
        "Pro_16",
        "Pro_17",
        "Pro_18",
        "Pro_19",
        "Pro_20",
        "Pro_21",
        "Pro_22",
        "Pro_23",
        "Pro_24",
        "Pro_25",
        "Pro_26",
        "Pro_27",
        "Pro_28",
        "Pro_29",
        "Pro_30",
        "Pro_31",
        "Pro_32",
        "Pro_33",
        "Pro_34",
        "Pro_35",
        "Pro_36",
        "Pro_37",
        "Pro_38",
        "Pro_39",
        "Pro_40",
        "Pro_41",
        "Pro_42",
        "Pro_43",
        "Pro_44",
        "Pro_45",
        "Pro_46",
        "Pro_47",
        "Pro_48",
        "Pro_49",
        "Pro_50",
        "Ger_01",
        "Ger_02",
        "Ger_03",
        "Ger_04",
        "Ger_05",
        "Ger_06",
        "Ger_07",
        "Ger_08",
        "Ger_09",
        "Ger_10",
        "Ger_11",
        "Ger_12",
        "Ger_13",
        "Ger_14",
        "Ger_15",
        "Ger_16",
        "Ger_17",
        "Ger_18",
        "Ger_19",
        "Ger_20",
        "Of_A1",
        "Of_E1",
        "Of_G1",
        "Of_G2",
        "Pro_51",
        "Pro_52",
        "Pro_53",
        "Pro_54",
        "1_Obra_Ajuste",
        "2_Obra_Ajuste",
        "Ger_00",
        "Of_00",
        "Pro_00",
        "Sup_00",
        "Ope_00"
    ],
        'proceso' => [
        "Liquidación Mensual",
        "Finiquito Quincena",
        "Finiquito Mensual",
        "Pago Fuera Proceso",
        "En Acreditación"
    ],
        'tipo_transfer' => [
        "Normal",
        "Reliquidación",
        "Reliquidación Especial",
        "Abono Fondo x Rendir",
        "Reliquidación Abono FxR",
        "Semana 1",
        "Semana 2",
        "Semana 3",
        "Semana 4",
        "Semana 5",
        "Retraso VB°"
    ],
        'discapacidad' => [
        "Sí",
        "No"
    ],
        'invalidez' => [
        "No",
        "Pensionado con Invalidez Parcial",
        "Asignatario Pensión por Invalidez Total"
    ],
    ];
}

/** Las 7 AFP vigentes (Capital..Uno) -- fuera de esta lista, se alerta al JAO. */
function afpVigentes(): array
{
    return [
        "Capital",
        "Cuprum",
        "Habitat",
        "Modelo",
        "PlanVital",
        "ProVida",
        "Uno"
    ];
}

/** Región (clave) => lista de comunas EXACTAS de esa región, ordenadas alfabéticamente. */
function regionesConComunas(): array
{
    return [
        "XV: de Arica y Parinacota" => [
        "Arica",
        "Camarones",
        "General Lagos",
        "Putre"
    ],
        "I: de Tarapacá" => [
        "Alto Hospicio",
        "Camiña",
        "Colchane",
        "Huara",
        "Iquique",
        "Pica",
        "Pozo Almonte"
    ],
        "II: de Antofagasta" => [
        "Antofagasta",
        "Calama",
        "María Elena",
        "Mejillones",
        "Ollagüe",
        "San Pedro de Atacama",
        "Sierra Gorda",
        "Taltal",
        "Tocopilla"
    ],
        "III: de Atacama" => [
        "Alto del Carmen",
        "Caldera",
        "Chañaral",
        "Copiapó",
        "Diego de Almagro",
        "Freirina",
        "Huasco",
        "Tierra Amarilla",
        "Vallenar"
    ],
        "IV: de Coquimbo" => [
        "Andacollo",
        "Canela",
        "Combarbalá",
        "Coquimbo",
        "Illapel",
        "La Higuera",
        "La Serena",
        "Los Vilos",
        "Monte Patria",
        "Ovalle",
        "Paihuano",
        "Punitaqui",
        "Río Hurtado",
        "Salamanca",
        "Vicuña"
    ],
        "V: de Valparaíso" => [
        "Algarrobo",
        "Cabildo",
        "Calle Larga",
        "Cartagena",
        "Casablanca",
        "Catemu",
        "Concón",
        "El Quisco",
        "El Tabo",
        "Hijuelas",
        "Isla de Pascua",
        "Juan Fernández",
        "La Calera",
        "La Cruz",
        "La Ligua",
        "Limache",
        "Llay Llay",
        "Los Andes",
        "Nogales",
        "Olmué",
        "Panquehue",
        "Papudo",
        "Petorca",
        "Puchuncaví",
        "Putaendo",
        "Quillota",
        "Quilpué",
        "Quintero",
        "Rinconada",
        "San Antonio",
        "San Esteban",
        "San Felipe",
        "Santa María",
        "Santo Domingo",
        "Valparaíso",
        "Villa Alemana",
        "Viña del Mar",
        "Zapallar"
    ],
        "VI: del Libertador Gral. Bernardo O'Higgins" => [
        "Chimbarongo",
        "Chépica",
        "Codegua",
        "Coinco",
        "Coltauco",
        "Doñihue",
        "Graneros",
        "La Estrella",
        "Las Cabras",
        "Litueche",
        "Lolol",
        "Machalí",
        "Malloa",
        "Marchihue",
        "Mostazal",
        "Nancagua",
        "Navidad",
        "Olivar",
        "Palmilla",
        "Paredones",
        "Peralillo",
        "Peumo",
        "Pichidegua",
        "Pichilemu",
        "Placilla",
        "Pumanque",
        "Quinta de Tilcoco",
        "Rancagua",
        "Rengo",
        "Requínoa",
        "San Fernando",
        "San Vicente",
        "Santa Cruz"
    ],
        "VII: del Maule" => [
        "Cauquenes",
        "Chanco",
        "Colbún",
        "Constitución",
        "Curepto",
        "Curicó",
        "Empedrado",
        "Hualañé",
        "Licantén",
        "Linares",
        "Longaví",
        "Maule",
        "Molina",
        "Parral",
        "Pelarco",
        "Pelluhue",
        "Pencahue",
        "Rauco",
        "Retiro",
        "Romeral",
        "Río Claro",
        "Sagrada Familia",
        "San Clemente",
        "San Javier",
        "San Rafael",
        "Talca",
        "Teno",
        "Vichuquén",
        "Villa Alegre",
        "Yerbas Buenas"
    ],
        "XVI: de Ñuble" => [
        "Bulnes",
        "Chillán",
        "Chillán Viejo",
        "Cobquecura",
        "Coelemu",
        "Coihueco",
        "El Carmen",
        "Ninhue",
        "Pemuco",
        "Pinto",
        "Portezuelo",
        "Quillón",
        "Quirihue",
        "Ránquil",
        "San Carlos",
        "San Fabián",
        "San Ignacio",
        "San Nicolás",
        "Treguaco",
        "Yungay",
        "Ñiquén"
    ],
        "VIII: del Biobío" => [
        "Alto Biobío",
        "Antuco",
        "Arauco",
        "Cabrero",
        "Cañete",
        "Chiguayante",
        "Concepción",
        "Contulmo",
        "Coronel",
        "Curanilahue",
        "Florida",
        "Hualpén",
        "Hualqui",
        "Laja",
        "Lebu",
        "Los Álamos",
        "Los Ángeles",
        "Lota",
        "Mulchén",
        "Nacimiento",
        "Negrete",
        "Penco",
        "Quilaco",
        "Quilleco",
        "San Pedro de la Paz",
        "San Rosendo",
        "Santa Bárbara",
        "Santa Juana",
        "Talcahuano",
        "Tirúa",
        "Tomé",
        "Tucapel",
        "Yumbel"
    ],
        "IX: de la Araucanía" => [
        "Angol",
        "Carahue",
        "Cholchol",
        "Collipulli",
        "Cunco",
        "Curacautín",
        "Curarrehue",
        "Ercilla",
        "Freire",
        "Galvarino",
        "Gorbea",
        "Lautaro",
        "Loncoche",
        "Lonquimay",
        "Los Sauces",
        "Lumaco",
        "Melipeuco",
        "Nueva Imperial",
        "Padre las Casas",
        "Perquenco",
        "Pitrufquén",
        "Pucón",
        "Purén",
        "Renaico",
        "Saavedra",
        "Temuco",
        "Teodoro Schmidt",
        "Toltén",
        "Traiguén",
        "Victoria",
        "Vilcún",
        "Villarrica"
    ],
        "XIV: de Los Ríos" => [
        "Corral",
        "Futrono",
        "La Unión",
        "Lago Ranco",
        "Lanco",
        "Los Lagos",
        "Mariquina",
        "Máfil",
        "Paillaco",
        "Panguipulli",
        "Río Bueno",
        "Valdivia"
    ],
        "X: de Los Lagos" => [
        "Ancud",
        "Calbuco",
        "Castro",
        "Chaitén",
        "Chonchi",
        "Cochamó",
        "Curaco de Vélez",
        "Dalcahue",
        "Fresia",
        "Frutillar",
        "Futaleufú",
        "Hualaihué",
        "Llanquihue",
        "Los Muermos",
        "Maullín",
        "Osorno",
        "Palena",
        "Puerto Montt",
        "Puerto Octay",
        "Puerto Varas",
        "Puqueldón",
        "Purranque",
        "Puyehue",
        "Queilén",
        "Quellón",
        "Quemchi",
        "Quinchao",
        "Río Negro",
        "San Juan de la Costa",
        "San Pablo"
    ],
        "XI: de Aysén del Gral. Carlos Ibáñez del Campo" => [
        "Aysén",
        "Chile Chico",
        "Cisnes",
        "Cochrane",
        "Coyhaique",
        "Guaitecas",
        "Lago Verde",
        "O'Higgins",
        "Río Ibáñez",
        "Tortel"
    ],
        "XII: de Magallanes y de la Antártica Chilena" => [
        "Antártica",
        "Cabo de Hornos",
        "Laguna Blanca",
        "Natales",
        "Porvenir",
        "Primavera",
        "Punta Arenas",
        "Río Verde",
        "San Gregorio",
        "Timaukel",
        "Torres del Paine"
    ],
        "RM: Metropolitana de Santiago" => [
        "Alhué",
        "Buin",
        "Calera de Tango",
        "Cerrillos",
        "Cerro Navia",
        "Colina",
        "Conchalí",
        "Curacaví",
        "El Bosque",
        "El Monte",
        "Estación Central",
        "Huechuraba",
        "Independencia",
        "Isla de Maipo",
        "La Cisterna",
        "La Florida",
        "La Granja",
        "La Pintana",
        "La Reina",
        "Lampa",
        "Las Condes",
        "Lo Barnechea",
        "Lo Espejo",
        "Lo Prado",
        "Macul",
        "Maipú",
        "María Pinto",
        "Melipilla",
        "Padre Hurtado",
        "Paine",
        "Pedro Aguirre Cerda",
        "Peñaflor",
        "Peñalolén",
        "Pirque",
        "Providencia",
        "Pudahuel",
        "Puente Alto",
        "Quilicura",
        "Quinta Normal",
        "Recoleta",
        "Renca",
        "San Bernardo",
        "San Joaquín",
        "San José de Maipo",
        "San Miguel",
        "San Pedro",
        "San Ramón",
        "Santiago",
        "Talagante",
        "Tiltil",
        "Vitacura",
        "Ñuñoa"
    ],
    ];
}